# Generated by Django 5.1.2 on 2026-01-13 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LayoutArmazem',
            fields=[
                ('gp', models.IntegerField(verbose_name='Galpão (GP)')),
                ('rua', models.IntegerField(primary_key=True, serialize=False, verbose_name='Código Rua (ID)')),
                ('largura_colunas', models.IntegerField(verbose_name='Largura (Colunas)')),
                ('base_footprint', models.IntegerField(verbose_name='Base (Chão)')),
                ('cap_nivel_1', models.IntegerField(verbose_name='Cap. Nível 1')),
                ('cap_nivel_2', models.IntegerField(verbose_name='Cap. Nível 2')),
                ('cap_maxima', models.IntegerField(verbose_name='Capacidade Total (N3)')),
                ('tipo_armazem', models.CharField(default='COBERTO', max_length=50)),
                ('altura_max_perm', models.IntegerField(default=3)),
            ],
            options={
                'verbose_name': 'Layout da Rua',
                'verbose_name_plural': 'Layouts das Ruas',
                'ordering': ['rua'],
            },
        ),
        migrations.CreateModel(
            name='InventarioDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_referencia', models.DateField(db_index=True, verbose_name='Data do Inventário')),
                ('data_importacao', models.DateTimeField(auto_now_add=True)),
                ('sku', models.CharField(max_length=20, verbose_name='Item')),
                ('descricao', models.CharField(max_length=200, verbose_name='Material')),
                ('tipo_produto', models.CharField(blank=True, max_length=10, null=True)),
                ('quantidade_paletes', models.FloatField(verbose_name='Qtd Paletes')),
                ('qtd_estoque_un', models.FloatField(blank=True, null=True, verbose_name='Qtd Unidades')),
                ('lote', models.CharField(blank=True, max_length=50, null=True)),
                ('data_producao', models.DateField(blank=True, null=True)),
                ('data_validade', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='ESTOQUE', max_length=50)),
                ('rua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoque_atual', to='core.layoutarmazem')),
            ],
            options={
                'verbose_name': 'Registro de Inventário',
                'indexes': [models.Index(fields=['data_referencia', 'rua', 'sku'], name='core_invent_data_re_ba79c6_idx')],
            },
        ),
    ]
