# Generated by Django 5.1.2 on 2026-01-20 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Cliente')),
                ('tipo_restricao', models.CharField(choices=[('DIAS_PRODUCAO', 'Máximo de Dias desde Produção (Idade)'), ('MIN_SHELF_LIFE', 'Mínimo de Shelf Life Restante (%)')], default='MIN_SHELF_LIFE', max_length=20, verbose_name='Tipo de Regra')),
                ('valor_restricao', models.IntegerField(help_text='Ex: 80 (para 80%) ou 30 (para 30 dias de idade máx)', verbose_name='Valor da Regra')),
            ],
            options={
                'verbose_name': 'Regra de Cliente (SLA)',
                'verbose_name_plural': 'Regras de Clientes (SLA)',
            },
        ),
        migrations.CreateModel(
            name='LayoutArmazem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gp', models.IntegerField(default=1)),
                ('rua', models.CharField(max_length=50, verbose_name='Rua / Endereço')),
                ('largura_colunas', models.IntegerField(verbose_name='Largura (Colunas)')),
                ('base_footprint', models.IntegerField(verbose_name='Base (Chão)')),
                ('cap_nivel_1', models.IntegerField(verbose_name='Cap. Nível 1')),
                ('cap_nivel_2', models.IntegerField(verbose_name='Cap. Nível 2')),
                ('cap_maxima', models.IntegerField(verbose_name='Capacidade Total (N3)')),
                ('tipo_armazem', models.CharField(default='COBERTO', max_length=50)),
                ('altura_max_perm', models.IntegerField(default=3)),
            ],
            options={
                'verbose_name': 'Layout da Rua',
                'verbose_name_plural': 'Layouts das Ruas',
                'ordering': ['rua'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('sku', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='SKU')),
                ('descricao', models.CharField(max_length=200, verbose_name='Produto')),
                ('familia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Família')),
                ('tipo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo')),
                ('shelf_life_dias', models.IntegerField(default=0, verbose_name='Shelf Life (Dias)')),
                ('unidade_por_pack', models.IntegerField(default=1, verbose_name='Unid/Pack')),
                ('embalagem_geral', models.CharField(blank=True, max_length=100, null=True, verbose_name='Emb. Geral')),
                ('paletizacao', models.IntegerField(default=0, verbose_name='Paletização (Packs/Pal)')),
                ('empilhamento_max', models.IntegerField(default=1, verbose_name='Empilhamento Máx')),
            ],
            options={
                'verbose_name': 'Cadastro Mestre (Produto)',
                'verbose_name_plural': 'Cadastro Mestre (Produtos)',
            },
        ),
        migrations.CreateModel(
            name='InventarioDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_referencia', models.DateField(db_index=True, verbose_name='Data do Inventário')),
                ('data_importacao', models.DateTimeField(auto_now_add=True)),
                ('sku', models.CharField(max_length=20, verbose_name='Item')),
                ('descricao', models.CharField(max_length=200, verbose_name='Material')),
                ('tipo_produto', models.CharField(blank=True, max_length=10, null=True)),
                ('quantidade_paletes', models.FloatField(verbose_name='Qtd Paletes')),
                ('qtd_estoque_un', models.FloatField(blank=True, null=True, verbose_name='Qtd Unidades')),
                ('lote', models.CharField(blank=True, max_length=50, null=True)),
                ('data_producao', models.DateField(blank=True, null=True)),
                ('data_validade', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='ESTOQUE', max_length=50)),
                ('rua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoque_atual', to='core.layoutarmazem')),
            ],
            options={
                'verbose_name': 'Registro de Inventário',
                'indexes': [models.Index(fields=['data_referencia', 'rua', 'sku'], name='core_invent_data_re_ba79c6_idx')],
            },
        ),
    ]
