# Generated by Django 5.1.2 on 2026-01-21 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariodiario',
            name='fracao',
            field=models.IntegerField(default=0, verbose_name='Fração / Unidades'),
        ),
    ]
