# Generated by Django 5.1.2 on 2026-01-16 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('sku', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Código SKU')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('shelf_life_dias', models.IntegerField(verbose_name='Shelf Life (Dias)')),
                ('alertar_em', models.IntegerField(default=30, verbose_name='Alerta Crítico (Dias)')),
            ],
            options={
                'verbose_name': 'Cadastro de Produto',
                'verbose_name_plural': 'Cadastro de Produtos',
            },
        ),
    ]
