# Generated by Django 5.1.2 on 2026-01-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_inventariodiario_fracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.CharField(max_length=255, verbose_name='Produto / Descrição'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='sku',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='SKU / Código'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('PA', 'PA'), ('INSUMO', 'INSUMO'), ('RPM', 'RPM')], default='PA', max_length=20, verbose_name='Tipo (Categoria)'),
        ),
    ]
