# Generated by Django 5.1.2 on 2026-01-16 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_produto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'verbose_name': 'Cadastro Mestre (Produto)', 'verbose_name_plural': 'Cadastro Mestre (Produtos)'},
        ),
        migrations.RemoveField(
            model_name='produto',
            name='alertar_em',
        ),
        migrations.AddField(
            model_name='produto',
            name='embalagem_geral',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Emb. Geral'),
        ),
        migrations.AddField(
            model_name='produto',
            name='empilhamento_max',
            field=models.IntegerField(default=1, verbose_name='Empilhamento Máx'),
        ),
        migrations.AddField(
            model_name='produto',
            name='familia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Família'),
        ),
        migrations.AddField(
            model_name='produto',
            name='paletizacao',
            field=models.IntegerField(default=0, verbose_name='Paletização (Packs/Pal)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='produto',
            name='unidade_por_pack',
            field=models.IntegerField(default=1, verbose_name='Unid/Pack'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.CharField(max_length=200, verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='shelf_life_dias',
            field=models.IntegerField(default=0, verbose_name='Shelf Life (Dias)'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='sku',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='SKU'),
        ),
    ]
