# Generated by Django 5.1.2 on 2026-01-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_produto_descricao_alter_produto_sku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='empilhamento',
            field=models.IntegerField(default=1, verbose_name='Empilhamento Máximo'),
        ),
    ]
