# Generated by Django 5.1.2 on 2026-01-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_produto_options_remove_produto_alertar_em_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Cliente')),
                ('tipo_restricao', models.CharField(choices=[('DIAS_PRODUCAO', 'Máximo de Dias desde Produção (Idade)'), ('MIN_SHELF_LIFE', 'Mínimo de Shelf Life Restante (%)')], default='MIN_SHELF_LIFE', max_length=20, verbose_name='Tipo de Regra')),
                ('valor_restricao', models.IntegerField(help_text='Ex: 80 (para 80%) ou 30 (para 30 dias de idade máx)', verbose_name='Valor da Regra')),
            ],
            options={
                'verbose_name': 'Regra de Cliente (SLA)',
                'verbose_name_plural': 'Regras de Clientes (SLA)',
            },
        ),
    ]
